#!/bin/bash

TARGET=$1
DEBROOT=$(pwd)

if [ "$(id -u)" != "0" ]; then
	echo "You have to run this as root!"
	exit 1
fi

[ -z "$1" ] && exit 1
ls $1 || exit 1
ls ${1}1 || exit 1

mount ${1}1 /mnt

export KVER=$(cd $DEBROOT/build/linux/; make kernelversion)

echo "Installing kernel and devicetree..."
cp $DEBROOT/build/linux/arch/arm64/boot/Image /mnt/Image
cp $DEBROOT/build/linux/arch/arm64/boot/dts/rockchip/rk3326-odroid-go2.dtb /mnt/odroidgo2.dtb

make -C $DEBROOT/build/linux ARCH=arm64 INSTALL_MOD_PATH=/mnt/ modules_install

#install -m 0644 $DEBROOT/build/esp8089/esp8089.ko "/mnt/lib/modules/$KVER/kernel/drivers/net/wireless/esp8089.ko"

chroot /mnt/ /sbin/depmod -a $KVER
#echo "options esp8089 esp_reset_gpio=105" > /mnt/etc/modprobe.d/esp.conf

umount /mnt
sync

echo 'Done!'
