#!/bin/bash

set -e

DEBROOT=$(pwd)

# envvars
export CROSS_COMPILE=aarch64-linux-gnu-

# make sure that we have build directory
mkdir -p build
cd build

# let's have a clean tree
rm -rf uboot
rm -rf arm-trusted-firmware

cd $DEBROOT/build
git clone https://github.com/ARM-software/arm-trusted-firmware.git
cd arm-trusted-firmware
make PLAT=px30 DEBUG=1 bl31 -j$(nproc)


export BL31=$DEBROOT/build/arm-trusted-firmware/build/px30/debug/bl31/bl31.elf
export ARCH=arm

cd $DEBROOT/build
git clone https://github.com/u-boot/u-boot.git uboot
cd uboot
cp $DEBROOT/res/uboot-config ./.config
cp $DEBROOT/res/uboot-env ./
make -j$(nproc)

# TODO: test it
#./tools/mkimage -n px30 -T rkspi -d spl/u-boot-spl-dtb.bin spl.bin
#dd if=spl.bin of=spl-out.bin bs=128K conv=sync
#cat spl-out.bin u-boot-dtb.img >out.bin
#dd if=out.bin of=u-boot-spi-out.img bs=4M conv=sync
