#!/bin/bash

TARGET=$1
DEBROOT=$(pwd)

if [ "$(id -u)" != "0" ]; then
	echo "You have to run this as root!"
	exit 1
fi

[ -z "$1" ] && exit 1

read -p "Are you sure $1 is correct device, press enter to continue"


echo "Making rootfs..."
# automated fdisk input: o n p 1 \n \n w, make one msdos part spanning entire drive
printf "o\nn\np\n1\n\n\nw" | fdisk /dev/sdc
sleep 2
/sbin/partx /dev/sdc
sleep 2
mkfs.ext4 /dev/sdc1

mount /dev/sdc1 /mnt
debootstrap --arch=arm64 sid /mnt http://deb.debian.org/debian/
echo odroidgo2 > /mnt/etc/hostname
cp $(which qemu-aarch64-static) /mnt/
chroot /mnt/ /qemu-aarch64-static /bin/passwd -d root


echo "Installing kernel and devicetree..."
cp $DEBROOT/build/linux/arch/arm64/boot/Image /mnt/Image
cp $DEBROOT/build/linux/arch/arm64/boot/dts/rockchip/rk3326-odroid-go2.dtb /mnt/odroidgo2.dtb

umount /mnt

echo "Installing Das U-Boot..."

cd build
cd uboot

dd if=idbloader.img of=$1 bs=512 seek=64 status=none
dd if=u-boot.itb of=$1 bs=512 seek=512 status=none
sync

echo 'Done!'
