#!/bin/bash

set -e

DEBROOT=$(pwd)

export ARCH=arm64
export CROSS_COMPILE=aarch64-linux-gnu-

# make sure that we have build directory
mkdir -p build
cd build

# download linux

if [ "$(date +'%V%y')" != "$(cat kern-dl-date)" ]; then
	date +'%V%y' > kernl-dl-date
	if [ -d 'linux' ]; then
		cd linux
		git pull
	else
		mkdir -p linux
		git clone https://github.com/Maccraft123/linux --single-branch -b odroidgo
	fi
fi

# yes that should be uppercase to not mess with tab completion
cd linux

# build
cp $DEBROOT/res/linux-config ./.config
make oldconfig
make -j$(nproc)
