#!/bin/bash

TARGET=$1
DEBROOT=$(pwd)

set -e
set -v

if [ "$(id -u)" != "0" ]; then
	echo "You have to run this as root!"
	exit 1
fi

[ -z "$1" ] && exit 1

read -p "Are you sure $1 is correct device, press enter to continue"
sleep 1

if echo $PATH | grep -E '^/sbin|:/sbin'; then echo -n ''; else
	echo "/sbin not in \$PATH"
	exit 1
fi


echo "Making rootfs..."
# automated fdisk input: o n p 1 \n \n w, make one msdos part spanning entire drive
printf "o\nn\np\n1\n\n\nw" | fdisk $1 || true
sleep 2
partx $1
sleep 2
mkfs.ext4 -F ${1}1

mount ${1}1 /mnt

cp $(which qemu-aarch64-static) /mnt/

if [ -z "$SUITE" ]; then
	qemu-debootstrap --arch=arm64 sid /mnt https://deb.debian.org/debian/ || true
else
	qemu-debootstrap --arch=arm64 $SUITE /mnt https://deb.debian.org/debian/
fi

echo odroidgo2 > /mnt/etc/hostname
chroot /mnt/ /qemu-aarch64-static /bin/passwd -d root


export KVER=$(cd $DEBROOT/build/linux/; make kernelversion)

echo "Installing kernel and devicetree..."
cp $DEBROOT/build/linux/arch/arm64/boot/Image /mnt/Image
cp $DEBROOT/build/linux/arch/arm64/boot/dts/rockchip/rk3326-odroid-go2.dtb /mnt/odroidgo2.dtb
make -C $DEBROOT/build/linux ARCH=arm64 INSTALL_MOD_PATH=/mnt/ modules_install
#mkdir -p "/mnt/lib/modules/5.8.13/kernel/drivers/net/wireless/" # TODO: dynamic
#install -Dm644 $DEBROOT/build/esp8089/esp8089.ko "/mnt/lib/modules/5.8.13/kernel/drivers/net/wireless/esp8089.ko"
chroot /mnt/ /qemu-aarch64-static /sbin/depmod -a $KVER

if [ -n "$UI" ]; then
	$DEBROOT/make-mesa
	chroot /mnt/ /qemu-aarch64-static /usr/sbin/useradd -c "GO2" -m user -G video,audio,render,input -s /bin/bash
	mkdir -p /mnt/etc/systemd/system/getty@tty1.service.d/
	printf '[Service]
ExecStart=
ExecStart=-/usr/sbin/agetty --autologin user --noclear %%I $TERM
	' > /mnt/etc/systemd/system/getty@tty1.service.d/override.conf
	chroot /mnt/ /qemu-aarch64-static /bin/apt install -y sway
	echo 'export WLR_LIBINPUT_NO_DEVICES=1' >> /mnt/home/user/.bashrc
	echo 'tty | grep tty1 && exec sway' >> /mnt/home/user/.bashrc
	if [ "$UI" = "retroarch" ]; then
		chroot /mnt/ /qemu-aarch64-static /bin/apt install -y retroarch xwayland
		#cp $DEBROOT/res/retroarch.cfg /mnt/etc/retroarch.cfg
		printf 'output DSI-1 transform 270\nexec retroarch\n' > /mnt/etc/sway/config
	fi
fi
#echo "options esp8089 esp_reset_gpio=105" > /mnt/modprobe.d/esp.conf
[ -n "$ADDPKGS" ] && chroot /mnt/ /qemu-aarch64-static /bin/apt install -y $ADDPKGS

echo "Installing Das U-Boot..."

cp $DEBROOT/build/uboot/idbloader.img $DEBROOT/build/uboot/u-boot.itb /mnt/

echo "To flash U-Boot to internal spi, refer to XXX"

umount /mnt

cd build
cd uboot

dd if=idbloader.img of=$1 bs=512 seek=64 status=none
dd if=u-boot.itb of=$1 bs=512 seek=512 status=none
sync

echo 'Done!'
